#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
INPUT_PATH = REPO_ROOT / "scripts/generate/data/languages.json"
OUTPUT_PATH = REPO_ROOT / "crates/engine/src/languages.rs"
I18N_OUTPUT_PATHS = {
    "en": REPO_ROOT / "apps/desktop/flutter/lib/src/i18n/en.i18n.json",
    "es": REPO_ROOT / "apps/desktop/flutter/lib/src/i18n/es.i18n.json",
    "fr": REPO_ROOT / "apps/desktop/flutter/lib/src/i18n/fr.i18n.json",
    "ja": REPO_ROOT / "apps/desktop/flutter/lib/src/i18n/ja.i18n.json",
    "ko": REPO_ROOT / "apps/desktop/flutter/lib/src/i18n/ko.i18n.json",
    "zh-Hans": REPO_ROOT / "apps/desktop/flutter/lib/src/i18n/zh-Hans.i18n.json",
    "zh-Hant": REPO_ROOT / "apps/desktop/flutter/lib/src/i18n/zh-Hant.i18n.json",
}
GENERATED_HEADER = "// This file is automatically generated. Do not edit by hand."
LANGUAGE_CODE_PATTERN = re.compile(r"^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$")
DEPRECATED_CODES = {
    "iw": "he",
    "ji": "yi",
    "jw": "jv",
    "in": "id",
}
APP_DISPLAY_LANGUAGES = ("en", "es", "fr", "ja", "ko", "zh-Hans", "zh-Hant")


def main() -> int:
    args = parse_args()
    try:
        languages = read_languages(args.input)
        validate_languages(languages)
    except (OSError, ValueError) as error:
        print(f"Failed to generate languages: {error}", file=sys.stderr)
        return 1

    output = render_rust_file(languages, args.input)
    if args.dry_run:
        print(output, end="")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output)
    print(f"Generated {len(languages)} languages -> {args.output}", flush=True)
    update_i18n_files(languages)
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Rust language data from the curated JSON list."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=INPUT_PATH,
        help="Curated JSON language list.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="Rust output file path.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated Rust to stdout without writing the output file.",
    )
    return parser.parse_args()


def read_languages(path: Path) -> list[dict[str, Any]]:
    raw = json.loads(path.read_text())
    if not isinstance(raw, dict):
        raise ValueError(f"{path} must contain a JSON object keyed by language code")

    languages: list[dict[str, Any]] = []
    for code in sorted(raw, key=str.casefold):
        entry = raw[code]
        if not isinstance(code, str) or not code.strip():
            raise ValueError("language code keys must be non-empty strings")
        if not isinstance(entry, dict):
            raise ValueError(f"language entry for {code} must be an object")
        local_name = entry.get("local_name")
        if not isinstance(local_name, str) or not local_name.strip():
            raise ValueError(f"local name for {code} must be a non-empty string")
        translations = entry.get("translations")
        if not isinstance(translations, dict):
            raise ValueError(f"translations for {code} must be an object")
        for language in APP_DISPLAY_LANGUAGES:
            translation = translations.get(language)
            if not isinstance(translation, str) or not translation.strip():
                raise ValueError(
                    f"translation for {code}.{language} must be a non-empty string"
                )
        languages.append(
            {"code": code, "local_name": local_name, "translations": translations}
        )
    return languages


def validate_languages(languages: list[dict[str, Any]]) -> None:
    seen: set[str] = set()
    for language in languages:
        code = language["code"]
        if not LANGUAGE_CODE_PATTERN.match(code):
            raise ValueError(f"invalid language code: {code}")
        if code in DEPRECATED_CODES:
            raise ValueError(
                f"deprecated language code {code}; use {DEPRECATED_CODES[code]} instead"
            )
        normalized = code.casefold()
        if normalized in seen:
            raise ValueError(f"duplicate language code: {code}")
        seen.add(normalized)


def render_rust_file(languages: list[dict[str, Any]], input_path: Path) -> str:
    source_path = input_path.relative_to(REPO_ROOT)
    lines = [
        GENERATED_HEADER,
        f"// Source: {source_path}",
        "",
        "use linguaray_core::LanguageInfo;",
        "",
        "/// Returns the curated language list supported by the app.",
        "pub fn all_languages() -> Vec<LanguageInfo> {",
        "    supported_languages()",
        "}",
        "",
        "/// Returns languages supported by the app UI.",
        "pub fn app_languages() -> Vec<LanguageInfo> {",
        "    let app_language_codes = [",
    ]
    for language in APP_DISPLAY_LANGUAGES:
        lines.append(f'        "{escape_rust_string(language)}",')
    lines.extend(
        [
            "    ];",
            "    let languages = supported_languages();",
            "    app_language_codes",
            "        .into_iter()",
            "        .filter_map(|code| languages.iter().find(|language| language.code == code).cloned())",
            "        .collect()",
            "}",
            "",
            "fn supported_languages() -> Vec<LanguageInfo> {",
            "    vec![",
        ]
    )
    for language in languages:
        lines.extend(
            [
                "        LanguageInfo {",
                f'            code: "{escape_rust_string(language["code"])}".to_owned(),',
                f'            local_name: "{escape_rust_string(language["local_name"])}".to_owned(),',
                "        },",
            ]
        )
    lines.extend(
        [
            "    ]",
            "}",
            "",
            "#[cfg(test)]",
            "mod tests {",
            "    use super::*;",
            "",
            "    #[test]",
            "    fn test_all_languages_is_not_empty() {",
            "        let languages = all_languages();",
            "        assert!(!languages.is_empty());",
            "    }",
            "",
            "    #[test]",
            "    fn test_all_languages_has_no_duplicates() {",
            "        let languages = all_languages();",
            "        let mut codes = languages",
            "            .iter()",
            "            .map(|l| l.code.as_str())",
            "            .collect::<Vec<_>>();",
            "        codes.sort_unstable();",
            "        codes.dedup();",
            "        assert_eq!(codes.len(), languages.len());",
            "    }",
            "",
            "    #[test]",
            "    fn test_all_languages_has_common_languages() {",
            "        let languages = all_languages();",
            "        let codes = languages",
            "            .iter()",
            "            .map(|l| l.code.as_str())",
            "            .collect::<Vec<_>>();",
            '        assert!(codes.contains(&"en"));',
            '        assert!(codes.contains(&"zh-Hans"));',
            '        assert!(codes.contains(&"zh-Hant"));',
            '        assert!(codes.contains(&"ja"));',
            '        assert!(codes.contains(&"ko"));',
            '        assert!(codes.contains(&"fr"));',
            '        assert!(codes.contains(&"de"));',
            '        assert!(codes.contains(&"es"));',
            '        assert!(codes.contains(&"ru"));',
            '        assert!(codes.contains(&"ar"));',
            '        assert!(codes.contains(&"jv"));',
            '        assert!(!codes.contains(&"iw"));',
            '        assert!(!codes.contains(&"jw"));',
            '        assert!(!codes.contains(&"kIs"));',
            "    }",
            "",
            "    #[test]",
            "    fn test_all_languages_local_names_are_populated() {",
            "        let languages = all_languages();",
            "        for lang in &languages {",
            "            assert!(",
            "                !lang.local_name.is_empty(),",
            '                "local_name for {} is empty",',
            "                lang.code",
            "            );",
            "        }",
            "    }",
            "",
            "    #[test]",
            "    fn test_app_languages_are_subset_of_all_languages() {",
            "        let languages = all_languages();",
            "        let app_languages = app_languages();",
            "        assert!(!app_languages.is_empty());",
            "        for app_language in &app_languages {",
            "            assert!(languages.iter().any(|language| language.code == app_language.code));",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def update_i18n_files(languages: list[dict[str, Any]]) -> None:
    for display_language, path in I18N_OUTPUT_PATHS.items():
        data = json.loads(path.read_text())
        common = data.setdefault("common", {})
        if not isinstance(common, dict):
            raise ValueError(f"{path}: common must be an object")
        common["language"] = {
            i18n_language_key(language["code"]): language["translations"][display_language]
            for language in languages
        }
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        print(f"Generated common.language translations -> {path}", flush=True)


def escape_rust_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def i18n_language_key(code: str) -> str:
    return code.lower().replace("-", "_")


if __name__ == "__main__":
    raise SystemExit(main())
