#!/usr/bin/env python3
from __future__ import annotations

import json
import platform
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PKG_DIR = REPO_ROOT / "packages/runtime"
RUST_DIR = PKG_DIR / "rust"
DART_OUT = PKG_DIR / "lib/src/generated"
SPM_DIR = PKG_DIR / "macos/linguaray_runtime/Sources"
SPM_SWIFT_OUT = SPM_DIR / "linguaray_runtime/Generated"
SPM_FFI_OUT = SPM_DIR / "linguaray_runtimeFFI/include"


def main() -> int:
    if not validate_inputs():
        return 1

    exit_code = run(
        ["cargo", "build", "--release", "--manifest-path", str(cargo_manifest())]
    )
    if exit_code != 0:
        return exit_code

    target_dir = cargo_target_dir()
    host_lib = host_cdylib(target_dir)
    if host_lib is None:
        print(f"Unsupported host OS: {platform.system()}", file=sys.stderr)
        return 1
    if not host_lib.exists():
        print(f"Host cdylib not found at {host_lib}", file=sys.stderr)
        return 1

    DART_OUT.mkdir(parents=True, exist_ok=True)
    SPM_SWIFT_OUT.mkdir(parents=True, exist_ok=True)
    SPM_FFI_OUT.mkdir(parents=True, exist_ok=True)

    print(f"==> Generating Swift bindings (uniffi-rs) -> {SPM_SWIFT_OUT}", flush=True)
    exit_code = run(
        [
            "cargo",
            "run",
            "--quiet",
            "--release",
            "--manifest-path",
            str(cargo_manifest()),
            "--bin",
            "uniffi-bindgen",
            "--",
            "generate",
            "--library",
            str(host_lib),
            "--language",
            "swift",
            "--out-dir",
            str(SPM_SWIFT_OUT),
        ]
    )
    if exit_code != 0:
        return exit_code

    print(f"==> Generating Dart bindings (uniffi-dart) -> {DART_OUT}", flush=True)
    exit_code = run(
        [
            "cargo",
            "run",
            "--quiet",
            "--release",
            "--manifest-path",
            str(cargo_manifest()),
            "--bin",
            "uniffi-bindgen-dart",
            "--",
            str(host_lib),
            str(DART_OUT),
        ]
    )
    if exit_code != 0:
        return exit_code

    sanitize_swift_bindings()
    deploy_ffi_artifacts()
    format_dart_output()
    print_generated_files()
    return 0


def validate_inputs() -> bool:
    if not cargo_manifest().exists():
        print(f"Missing Cargo manifest: {cargo_manifest()}", file=sys.stderr)
        return False
    return True


def cargo_manifest() -> Path:
    return RUST_DIR / "Cargo.toml"


def cargo_target_dir() -> Path:
    result = subprocess.run(
        [
            "cargo",
            "metadata",
            "--no-deps",
            "--format-version=1",
            "--manifest-path",
            str(cargo_manifest()),
        ],
        cwd=REPO_ROOT,
        check=False,
        stdout=subprocess.PIPE,
        text=True,
    )
    if result.returncode != 0:
        raise SystemExit(result.returncode)
    return Path(json.loads(result.stdout)["target_directory"])


def host_cdylib(target_dir: Path) -> Path | None:
    system = platform.system()
    if system == "Darwin":
        return target_dir / "release/liblinguaray_runtime.dylib"
    if system == "Linux":
        return target_dir / "release/liblinguaray_runtime.so"
    if system == "Windows" or system.startswith(("MSYS", "MINGW", "CYGWIN")):
        return target_dir / "release/linguaray_runtime.dll"
    return None


def format_dart_output() -> None:
    if shutil.which("dart") is None:
        return
    result = subprocess.run(
        ["dart", "format", str(DART_OUT)],
        cwd=REPO_ROOT,
        check=False,
        stdout=subprocess.DEVNULL,
    )
    if result.returncode != 0:
        print(
            "WARNING: dart format failed or is unavailable; proceeding without full formatting",
            file=sys.stderr,
        )


def sanitize_swift_bindings() -> None:
    generated_header = (
        "// This file is automatically generated. Do not edit by hand.\n\n"
    )
    sanitize_generated_header(SPM_SWIFT_OUT.glob("*.swift"), generated_header)
    sanitize_generated_header(
        SPM_SWIFT_OUT.glob("*.h"),
        "// This file is automatically generated. Do not edit by hand.\n",
    )


def sanitize_generated_header(paths, replacement: str) -> None:
    original = (
        "// This file was autogenerated by some "
        "hot "
        "garbage in the `uniffi` crate.\n"
        "// Trust "
        "me, you don't want to "
        "mess with it!\n"
        "\n"
    )
    for path in paths:
        source = path.read_text()
        source = source.replace(original, replacement, 1)
        had_final_newline = source.endswith("\n")
        source = "\n".join(line.rstrip() for line in source.splitlines())
        if had_final_newline:
            source += "\n"
        path.write_text(source)


def deploy_ffi_artifacts() -> None:
    """Move .h and .modulemap from the Swift output dir to the FFI target dir."""
    print(f"==> Deploying FFI artefacts -> {SPM_FFI_OUT}", flush=True)
    SPM_FFI_OUT.mkdir(parents=True, exist_ok=True)

    # Move the C header (uniffi-bindgen puts it alongside the .swift file)
    h_src = SPM_SWIFT_OUT / "linguaray_runtimeFFI.h"
    if h_src.exists():
        shutil.move(str(h_src), SPM_FFI_OUT / "linguaray_runtimeFFI.h")

    # Move and rename the modulemap
    mmap_src = SPM_SWIFT_OUT / "linguaray_runtimeFFI.modulemap"
    if mmap_src.exists():
        shutil.move(str(mmap_src), SPM_FFI_OUT / "module.modulemap")


def print_generated_files() -> None:
    print("Done. Generated files:")
    list_dir(SPM_SWIFT_OUT)
    list_dir(SPM_FFI_OUT)
    list_dir(DART_OUT)


def list_dir(path: Path) -> None:
    print(f"{path}:")
    for child in sorted(path.iterdir()):
        print(child.name)
    print()


def run(args: list[str]) -> int:
    result = subprocess.run(args, cwd=REPO_ROOT, check=False)
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
