use super::models::{
    field, AuthScheme, NetworkPolicy, ProviderCategory, ProviderPreset, Stability, BOTH_DESKTOPS,
    DICTIONARY_ONLY, LLM_TRANSLATION, MACOS_ONLY, SYSTEM_CAPABILITIES, TRANSLATION_ONLY,
};
use crate::engine::ProviderType;

const LLM_KEY_MODEL: &[super::models::ProviderFieldSpec] = &[
    field(
        "apiKey",
        "settings.providers.fields.api_key",
        true,
        true,
        false,
        None,
    ),
    field(
        "defaultModel",
        "settings.providers.fields.default_model",
        false,
        true,
        false,
        None,
    ),
    field(
        "baseUrl",
        "settings.providers.fields.base_url",
        false,
        false,
        true,
        None,
    ),
    field(
        "modelsUrl",
        "settings.providers.fields.models_url",
        false,
        false,
        true,
        None,
    ),
];

const LLM_OPTIONAL_KEY: &[super::models::ProviderFieldSpec] = &[
    field(
        "apiKey",
        "settings.providers.fields.api_key",
        true,
        false,
        false,
        None,
    ),
    field(
        "defaultModel",
        "settings.providers.fields.default_model",
        false,
        true,
        false,
        None,
    ),
    field(
        "baseUrl",
        "settings.providers.fields.base_url",
        false,
        false,
        true,
        None,
    ),
    field(
        "modelsUrl",
        "settings.providers.fields.models_url",
        false,
        false,
        true,
        None,
    ),
];

const OLLAMA_FIELDS: &[super::models::ProviderFieldSpec] = &[
    field(
        "defaultModel",
        "settings.providers.fields.default_model",
        false,
        true,
        false,
        None,
    ),
    field(
        "baseUrl",
        "settings.providers.fields.base_url",
        false,
        false,
        true,
        Some("http://127.0.0.1:11434"),
    ),
];

pub const PRESETS: &[ProviderPreset] = &[
    ProviderPreset {
        id: "system",
        engine_type: ProviderType::System,
        protocol: "system",
        category: ProviderCategory::BuiltIn,
        name: "System",
        description_key: "settings.providers.catalog.system",
        homepage_url: None,
        api_key_url: None,
        base_url: "",
        models_url: "",
        fields: &[],
        capabilities: SYSTEM_CAPABILITIES,
        auth_scheme: AuthScheme::None,
        supported_platforms: MACOS_ONLY,
        network_policy: NetworkPolicy::LocalOnly,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "ecdict",
        engine_type: ProviderType::Ecdict,
        protocol: "ecdict",
        category: ProviderCategory::BuiltIn,
        name: "ECDICT",
        description_key: "settings.providers.catalog.ecdict",
        homepage_url: Some("https://github.com/skywind3000/ECDICT"),
        api_key_url: None,
        base_url: "",
        models_url: "",
        fields: &[],
        capabilities: DICTIONARY_ONLY,
        auth_scheme: AuthScheme::None,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::LocalOnly,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "google-web",
        engine_type: ProviderType::GoogleWeb,
        protocol: "google_web",
        category: ProviderCategory::BuiltIn,
        name: "Google Web",
        description_key: "settings.providers.catalog.google_web",
        homepage_url: Some("https://translate.google.com"),
        api_key_url: None,
        base_url: "https://translate.google.com",
        models_url: "",
        fields: &[],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::None,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::UnofficialWeb,
        stability: Stability::Experimental,
    },
    ProviderPreset {
        id: "bing-web",
        engine_type: ProviderType::BingWeb,
        protocol: "bing_web",
        category: ProviderCategory::BuiltIn,
        name: "Bing Web",
        description_key: "settings.providers.catalog.bing_web",
        homepage_url: Some("https://www.bing.com/translator"),
        api_key_url: None,
        base_url: "https://api-edge.cognitive.microsofttranslator.com",
        models_url: "",
        fields: &[],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::Bearer,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::UnofficialWeb,
        stability: Stability::Experimental,
    },
    ProviderPreset {
        id: "tencent-transmart-web",
        engine_type: ProviderType::TencentTransmartWeb,
        protocol: "tencent_transmart_web",
        category: ProviderCategory::BuiltIn,
        name: "Tencent Transmart",
        description_key: "settings.providers.catalog.tencent_transmart_web",
        homepage_url: Some("https://transmart.qq.com"),
        api_key_url: None,
        base_url: "https://transmart.qq.com",
        models_url: "",
        fields: &[
            field(
                "username",
                "settings.providers.fields.username",
                false,
                false,
                false,
                None,
            ),
            field(
                "token",
                "settings.providers.fields.token",
                true,
                false,
                false,
                None,
            ),
        ],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::HeaderToken,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::UnofficialWeb,
        stability: Stability::Experimental,
    },
    ProviderPreset {
        id: "deepl-free",
        engine_type: ProviderType::DeepL,
        protocol: "deepl",
        category: ProviderCategory::TraditionalApi,
        name: "DeepL Free",
        description_key: "settings.providers.catalog.deepl_free",
        homepage_url: Some("https://www.deepl.com"),
        api_key_url: Some("https://www.deepl.com/pro-api"),
        base_url: "https://api-free.deepl.com",
        models_url: "",
        fields: &[field(
            "authKey",
            "settings.providers.fields.auth_key",
            true,
            true,
            false,
            None,
        )],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::DeepLAuthKey,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::OfficialApi,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "deepl-pro",
        engine_type: ProviderType::DeepL,
        protocol: "deepl",
        category: ProviderCategory::TraditionalApi,
        name: "DeepL Pro",
        description_key: "settings.providers.catalog.deepl_pro",
        homepage_url: Some("https://www.deepl.com"),
        api_key_url: Some("https://www.deepl.com/pro-api"),
        base_url: "https://api.deepl.com",
        models_url: "",
        fields: &[field(
            "authKey",
            "settings.providers.fields.auth_key",
            true,
            true,
            false,
            None,
        )],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::DeepLAuthKey,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::OfficialApi,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "google-cloud-translation",
        engine_type: ProviderType::Google,
        protocol: "google_cloud",
        category: ProviderCategory::TraditionalApi,
        name: "Google Cloud Translation",
        description_key: "settings.providers.catalog.google_cloud",
        homepage_url: Some("https://cloud.google.com/translate"),
        api_key_url: Some("https://console.cloud.google.com/apis/credentials"),
        base_url: "https://translation.googleapis.com",
        models_url: "",
        fields: &[field(
            "apiKey",
            "settings.providers.fields.api_key",
            true,
            true,
            false,
            None,
        )],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::QueryKey,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::OfficialApi,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "baidu-translate",
        engine_type: ProviderType::Baidu,
        protocol: "baidu",
        category: ProviderCategory::TraditionalApi,
        name: "Baidu Translate",
        description_key: "settings.providers.catalog.baidu",
        homepage_url: Some("https://fanyi-api.baidu.com"),
        api_key_url: Some("https://fanyi-api.baidu.com"),
        base_url: "https://fanyi-api.baidu.com",
        models_url: "",
        fields: &[
            field(
                "appId",
                "settings.providers.fields.app_id",
                false,
                true,
                false,
                None,
            ),
            field(
                "appKey",
                "settings.providers.fields.app_key",
                true,
                true,
                false,
                None,
            ),
        ],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::Custom,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::OfficialApi,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "tencent-cloud-tmt",
        engine_type: ProviderType::Tencent,
        protocol: "tencent",
        category: ProviderCategory::TraditionalApi,
        name: "Tencent Cloud TMT",
        description_key: "settings.providers.catalog.tencent_cloud",
        homepage_url: Some("https://cloud.tencent.com/product/tmt"),
        api_key_url: Some("https://console.cloud.tencent.com/cam/capi"),
        base_url: "https://tmt.tencentcloudapi.com",
        models_url: "",
        fields: &[
            field(
                "secretId",
                "settings.providers.fields.secret_id",
                true,
                true,
                false,
                None,
            ),
            field(
                "secretKey",
                "settings.providers.fields.secret_key",
                true,
                true,
                false,
                None,
            ),
        ],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::Custom,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::OfficialApi,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "youdao-zhiyun",
        engine_type: ProviderType::Youdao,
        protocol: "youdao",
        category: ProviderCategory::TraditionalApi,
        name: "Youdao Zhiyun",
        description_key: "settings.providers.catalog.youdao",
        homepage_url: Some("https://ai.youdao.com"),
        api_key_url: Some("https://ai.youdao.com"),
        base_url: "https://openapi.youdao.com",
        models_url: "",
        fields: &[
            field(
                "appKey",
                "settings.providers.fields.app_key",
                false,
                true,
                false,
                None,
            ),
            field(
                "appSecret",
                "settings.providers.fields.app_secret",
                true,
                true,
                false,
                None,
            ),
        ],
        capabilities: YOUDAO_CAPABILITIES,
        auth_scheme: AuthScheme::Custom,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::OfficialApi,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "caiyun",
        engine_type: ProviderType::Caiyun,
        protocol: "caiyun",
        category: ProviderCategory::TraditionalApi,
        name: "Caiyun",
        description_key: "settings.providers.catalog.caiyun",
        homepage_url: Some("https://docs.caiyunapp.com"),
        api_key_url: Some("https://dashboard.caiyunapp.com"),
        base_url: "https://api.interpreter.caiyunai.com",
        models_url: "",
        fields: &[
            field(
                "token",
                "settings.providers.fields.token",
                true,
                true,
                false,
                None,
            ),
            field(
                "requestId",
                "settings.providers.fields.request_id",
                false,
                true,
                false,
                None,
            ),
        ],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::HeaderToken,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::OfficialApi,
        stability: Stability::Stable,
    },
    llm_preset(
        "openai",
        ProviderType::OpenAi,
        "OpenAI",
        "settings.providers.catalog.openai",
        "https://platform.openai.com",
        "https://platform.openai.com/api-keys",
        "https://api.openai.com/v1",
    ),
    llm_preset(
        "anthropic",
        ProviderType::Anthropic,
        "Anthropic",
        "settings.providers.catalog.anthropic",
        "https://www.anthropic.com",
        "https://console.anthropic.com/settings/keys",
        "https://api.anthropic.com/v1",
    ),
    llm_preset(
        "gemini",
        ProviderType::Gemini,
        "Gemini",
        "settings.providers.catalog.gemini",
        "https://ai.google.dev",
        "https://aistudio.google.com/apikey",
        "https://generativelanguage.googleapis.com/v1beta/openai",
    ),
    llm_preset(
        "deepseek",
        ProviderType::DeepSeek,
        "DeepSeek",
        "settings.providers.catalog.deepseek",
        "https://www.deepseek.com",
        "https://platform.deepseek.com/api_keys",
        "https://api.deepseek.com/v1",
    ),
    llm_preset(
        "bailian-qwen",
        ProviderType::Qwen,
        "Bailian Qwen",
        "settings.providers.catalog.qwen",
        "https://www.aliyun.com/product/bailian",
        "https://bailian.console.aliyun.com",
        "https://dashscope.aliyuncs.com/compatible-mode/v1",
    ),
    llm_preset(
        "zhipu-bigmodel",
        ProviderType::Zhipu,
        "Zhipu BigModel",
        "settings.providers.catalog.zhipu",
        "https://open.bigmodel.cn",
        "https://open.bigmodel.cn/usercenter/apikeys",
        "https://open.bigmodel.cn/api/paas/v4",
    ),
    llm_preset(
        "moonshot-kimi",
        ProviderType::Moonshot,
        "Moonshot Kimi",
        "settings.providers.catalog.moonshot",
        "https://platform.moonshot.cn",
        "https://platform.moonshot.cn/console/api-keys",
        "https://api.moonshot.cn/v1",
    ),
    llm_preset(
        "doubao-ark",
        ProviderType::Doubao,
        "Doubao Ark",
        "settings.providers.catalog.doubao",
        "https://www.volcengine.com/product/doubao",
        "https://console.volcengine.com/ark",
        "https://ark.cn-beijing.volces.com/api/v3",
    ),
    llm_preset(
        "xai",
        ProviderType::XAi,
        "xAI",
        "settings.providers.catalog.xai",
        "https://x.ai",
        "https://console.x.ai",
        "https://api.x.ai/v1",
    ),
    llm_preset(
        "groq",
        ProviderType::Groq,
        "Groq",
        "settings.providers.catalog.groq",
        "https://groq.com",
        "https://console.groq.com/keys",
        "https://api.groq.com/openai/v1",
    ),
    llm_preset(
        "openrouter",
        ProviderType::OpenAiCompatible,
        "OpenRouter",
        "settings.providers.catalog.openrouter",
        "https://openrouter.ai",
        "https://openrouter.ai/keys",
        "https://openrouter.ai/api/v1",
    ),
    llm_preset(
        "siliconflow-cn",
        ProviderType::OpenAiCompatible,
        "SiliconFlow",
        "settings.providers.catalog.siliconflow_cn",
        "https://siliconflow.cn",
        "https://cloud.siliconflow.cn/account/ak",
        "https://api.siliconflow.cn/v1",
    ),
    llm_preset(
        "siliconflow-global",
        ProviderType::OpenAiCompatible,
        "SiliconFlow Global",
        "settings.providers.catalog.siliconflow_global",
        "https://www.siliconflow.com",
        "https://cloud.siliconflow.com/account/ak",
        "https://api.siliconflow.com/v1",
    ),
    llm_preset(
        "modelscope",
        ProviderType::OpenAiCompatible,
        "ModelScope",
        "settings.providers.catalog.modelscope",
        "https://modelscope.cn",
        "https://modelscope.cn/my/myaccesstoken",
        "https://api-inference.modelscope.cn/v1",
    ),
    ProviderPreset {
        id: "ollama",
        engine_type: ProviderType::Ollama,
        protocol: "ollama",
        category: ProviderCategory::LocalOrSelfHosted,
        name: "Ollama",
        description_key: "settings.providers.catalog.ollama",
        homepage_url: Some("https://ollama.com"),
        api_key_url: None,
        base_url: "http://127.0.0.1:11434",
        models_url: "http://127.0.0.1:11434/api/tags",
        fields: OLLAMA_FIELDS,
        capabilities: LLM_TRANSLATION,
        auth_scheme: AuthScheme::None,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::SelfHosted,
        stability: Stability::Stable,
    },
    local_llm(
        "lm-studio",
        "LM Studio",
        "settings.providers.catalog.lm_studio",
        "http://127.0.0.1:1234/v1",
    ),
    local_llm(
        "localai",
        "LocalAI",
        "settings.providers.catalog.localai",
        "http://127.0.0.1:8080/v1",
    ),
    local_llm(
        "vllm",
        "vLLM",
        "settings.providers.catalog.vllm",
        "http://127.0.0.1:8000/v1",
    ),
    local_llm(
        "llama-cpp",
        "llama.cpp",
        "settings.providers.catalog.llama_cpp",
        "http://127.0.0.1:8080/v1",
    ),
    local_llm(
        "litellm",
        "LiteLLM",
        "settings.providers.catalog.litellm",
        "http://127.0.0.1:4000/v1",
    ),
    ProviderPreset {
        id: "libretranslate",
        engine_type: ProviderType::LibreTranslate,
        protocol: "libretranslate",
        category: ProviderCategory::LocalOrSelfHosted,
        name: "LibreTranslate",
        description_key: "settings.providers.catalog.libretranslate",
        homepage_url: Some("https://docs.libretranslate.com"),
        api_key_url: None,
        base_url: "http://127.0.0.1:5000",
        models_url: "",
        fields: &[
            field(
                "apiKey",
                "settings.providers.fields.api_key",
                true,
                false,
                false,
                None,
            ),
            field(
                "baseUrl",
                "settings.providers.fields.base_url",
                false,
                false,
                true,
                Some("http://127.0.0.1:5000"),
            ),
        ],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::QueryKey,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::SelfHosted,
        stability: Stability::Stable,
    },
    ProviderPreset {
        id: "mtranserver",
        engine_type: ProviderType::MTranServer,
        protocol: "mtranserver",
        category: ProviderCategory::LocalOrSelfHosted,
        name: "MTranServer",
        description_key: "settings.providers.catalog.mtranserver",
        homepage_url: Some("https://github.com/xxnuo/MTranServer"),
        api_key_url: None,
        base_url: "http://127.0.0.1:8989",
        models_url: "",
        fields: &[
            field(
                "token",
                "settings.providers.fields.token",
                true,
                false,
                false,
                None,
            ),
            field(
                "baseUrl",
                "settings.providers.fields.base_url",
                false,
                false,
                true,
                Some("http://127.0.0.1:8989"),
            ),
        ],
        capabilities: TRANSLATION_ONLY,
        auth_scheme: AuthScheme::Bearer,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::SelfHosted,
        stability: Stability::Stable,
    },
];

const YOUDAO_CAPABILITIES: super::models::ProviderCapabilities =
    super::models::ProviderCapabilities {
        translation: true,
        dictionary: true,
        ocr: true,
        llm: false,
    };

const fn llm_preset(
    id: &'static str,
    engine_type: ProviderType,
    name: &'static str,
    description_key: &'static str,
    homepage: &'static str,
    api_key_url: &'static str,
    base_url: &'static str,
) -> ProviderPreset {
    ProviderPreset {
        id,
        engine_type,
        protocol: if matches!(engine_type, ProviderType::Anthropic) {
            "anthropic"
        } else {
            "openai_compatible"
        },
        category: if matches!(engine_type, ProviderType::OpenAiCompatible) {
            ProviderCategory::Aggregator
        } else {
            ProviderCategory::LlmOfficial
        },
        name,
        description_key,
        homepage_url: Some(homepage),
        api_key_url: Some(api_key_url),
        base_url,
        models_url: "",
        fields: LLM_KEY_MODEL,
        capabilities: LLM_TRANSLATION,
        auth_scheme: if matches!(engine_type, ProviderType::Anthropic) {
            AuthScheme::Anthropic
        } else {
            AuthScheme::Bearer
        },
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::OfficialApi,
        stability: Stability::Stable,
    }
}

const fn local_llm(
    id: &'static str,
    name: &'static str,
    description_key: &'static str,
    base_url: &'static str,
) -> ProviderPreset {
    ProviderPreset {
        id,
        engine_type: ProviderType::OpenAiCompatible,
        protocol: "openai_compatible",
        category: ProviderCategory::LocalOrSelfHosted,
        name,
        description_key,
        homepage_url: None,
        api_key_url: None,
        base_url,
        models_url: "",
        fields: LLM_OPTIONAL_KEY,
        capabilities: LLM_TRANSLATION,
        auth_scheme: AuthScheme::Bearer,
        supported_platforms: BOTH_DESKTOPS,
        network_policy: NetworkPolicy::SelfHosted,
        stability: Stability::Stable,
    }
}

pub fn preset_by_id(id: &str) -> Option<&'static ProviderPreset> {
    PRESETS.iter().find(|preset| preset.id == id)
}

pub fn presets_for_platform(macos: bool) -> Vec<&'static ProviderPreset> {
    PRESETS
        .iter()
        .filter(|preset| preset.available_on(macos))
        .collect()
}
