// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Translate the clipboard contents ONCE, on user demand.
	 * 
	 *  Reads the clipboard exactly once and surfaces the result in the popup window at
	 *  the current cursor position. Deliberately NOT a background listener — there is
	 *  no clipboard-changed subscription anywhere in the app (spec §Scope: user-initiated).
	 */
	translateClipboard: () => __TAURI_INVOKE<null>("translate_clipboard"),
	/**
	 *  并行/单引擎翻译命令（R2a）。前端用 `invoke('translate_session', { req })` 调用。
	 * 
	 *  从 AppState 读 active selection + providers，从 Session 读 client/keystore，
	 *  从 settings 读 fallback_engine。parallel 为空时退化为单引擎（actual_engine=Some）。
	 */
	translateSession: (req: TranslateSessionRequest) => __TAURI_INVOKE<TranslateSessionWire_Serialize>("translate_session", { req }),
	/**
	 *  A4 (P1-5): translate the live OS selection (fresh capture) OR a
	 *  caller-supplied SOURCE text (Retry). Distinct from `translate_clipboard`
	 *  which reads the clipboard — this NEVER reads the clipboard. The tray
	 *  `translate-selection` action and the popup Retry both route here.
	 * 
	 *  `text = Some(t)` (Retry): skip capture, use the saved SOURCE text.
	 *  `text = None` (tray): capture the selection fresh under the selection lock.
	 * 
	 *  Returns `Result<(), ()>` because the popup state is emitted via events —
	 *  there is no useful payload to return to the caller. Allocation of the
	 *  generation token + the capture+translate pipeline run on the async runtime
	 *  so the IPC call does not block on capture_selection (which simulates Cmd+C).
	 */
	translateSelectionIpc: (text: string | null) => __TAURI_INVOKE<null>("translate_selection_ipc", { text }),
	keyStatus: () => __TAURI_INVOKE<{ [key in string]: boolean }>("key_status"),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	setSetting: (key: string, value: string) => __TAURI_INVOKE<null>("set_setting", { key, value }),
	a11yStatus: () => __TAURI_INVOKE<boolean>("a11y_status"),
	/**
	 *  macOS Screen Recording permission (needed by region OCR). Preflighted —
	 *  never prompts. Non-macOS has no such gate and reports `true`.
	 */
	screenCaptureStatus: () => __TAURI_INVOKE<boolean>("screen_capture_status"),
	keystoreHealth: () => __TAURI_INVOKE<string>("keystore_health"),
	archiveKeystore: () => __TAURI_INVOKE<string>("archive_keystore"),
	resetKeystore: () => __TAURI_INVOKE<string | null>("reset_keystore"),
	/**
	 *  Official catalog rows for the Provider Center preset grid.
	 *  No DB / keystore — default deny except the main window capability.
	 */
	providerListPresets: () => __TAURI_INVOKE<CatalogPresetDto[]>("provider_list_presets"),
	/**  List active provider profiles (`status='active'`), ordered by `sort_order`. */
	providerList: () => __TAURI_INVOKE<ProviderProfile_Serialize[]>("provider_list"),
	/**
	 *  Create a new provider from a template (preset id). The preset catalog
	 *  derives protocol/endpoint/default-model/needs_key; caller values override
	 *  endpoint/model when non-empty.
	 */
	providerCreate: (templateId: string, name: string, endpoint: string, model: string | null) => __TAURI_INVOKE<ProviderProfile_Serialize>("provider_create", { templateId, name, endpoint, model }),
	/**
	 *  Apply a partial patch to a provider with optimistic-lock (CAS) semantics
	 *  (R2-E). An endpoint change is validated and may invalidate the parallel
	 *  consent (see `db_providers::update`). The patch's `expected_version` must
	 *  match the row's current `version`; a mismatch rejects with a structured
	 *  `{"error":"stale_version","actual_version":N}` so the UI can show a
	 *  save-conflict banner instead of clobbering the other writer's change.
	 */
	providerUpdate: (uuid: string, patch: ProviderPatch) => __TAURI_INVOKE<ProviderProfile_Serialize>("provider_update", { uuid, patch }),
	/**
	 *  Duplicate a provider. New UUID, new `secret_ref`, keyless (the original key
	 *  is never copied).
	 */
	providerDuplicate: (uuid: string) => __TAURI_INVOKE<ProviderProfile_Serialize>("provider_duplicate", { uuid }),
	/**
	 *  Begin the 3-step delete (mark `deleting`, evict from slots), purge the key
	 *  from the keystore, then finalize the tombstone. Each step is committed before
	 *  the next; the lock-order rule (DB Mutex and keystore flock never nested) is
	 *  preserved by releasing the DB guard between steps. All three steps run on one
	 *  blocking thread so the `data_gate` write guard spans the whole operation.
	 */
	providerDelete: (uuid: string) => __TAURI_INVOKE<null>("provider_delete", { uuid }),
	/**
	 *  Re-assign `sort_order` to the given UUID order. The list MUST be exactly the
	 *  set of active UUIDs.
	 */
	providerReorder: (uuids: string[]) => __TAURI_INVOKE<null>("provider_reorder", { uuids }),
	/**
	 *  Flip `enabled`. Disabling also evicts the row from selection slots and
	 *  invalidates parallel consent (mirrors `begin_delete`).
	 */
	providerToggle: (uuid: string, enabled: boolean) => __TAURI_INVOKE<null>("provider_toggle", { uuid, enabled }),
	/**
	 *  Set/clear a provider's API key in the keystore. The provider row's
	 *  `secret_ref` names the key. Cross-store (DB read → keystore write) but the
	 *  two locks are never held at once: the DB read releases before the keystore
	 *  RMW begins (lock-order rule). Both steps run on one blocking thread.
	 * 
	 *  R11: the command fast-fails on empty keys before spawning a thread, then
	 *  delegates to the synchronous, testable [`set_key_blocking`] core.
	 */
	providerSetKey: (uuid: string, key: string) => __TAURI_INVOKE<null>("provider_set_key", { uuid, key }),
	/**
	 *  Set the active selection (primary, parallel, fallback). Empty primary and
	 *  empty parallel list mean "no selection". Validates the selection against the
	 *  active provider set before writing.
	 * 
	 *  Review P1 #3 (multi-engine consent): when `parallel` is non-empty, the
	 *  backend recomputes the canonical consent scope and compares it against the
	 *  stored scope. A mismatch (no prior consent, or a different parallel set)
	 *  returns [`db_providers::ConsentError::ConsentRequired`] carrying the
	 *  `actual_scope`. The frontend shows the consent dialog, then calls
	 *  [`provider_confirm_and_set_active`] with `expected_scope = actual_scope` to
	 *  record the approval. A matching scope (re-affirming the same selection) is
	 *  written immediately.
	 */
	providerSetActive: (primary: string, parallel: string[], fallback: string | null) => __TAURI_INVOKE<SetActiveResult>("provider_set_active", { primary, parallel, fallback }),
	/**
	 *  popup/popup CTAs (Surface 02/03) so they can show a friendly engine label.
	 *  Returns the default (all-empty) selection if the DB is not ready yet.
	 */
	providerGetActiveSelection: () => __TAURI_INVOKE<ActiveSelection>("provider_get_active_selection"),
	/**
	 *  Confirm the user's explicit consent for a parallel selection and write it
	 *  atomically (P1 #3).
	 * 
	 *  Single DB transaction that:
	 *  1. Re-reads ALL active providers (inside the tx — no TOCTOU between the
	 *     `provider_set_active` probe and this confirm).
	 *  2. Validates the candidate selection (`validate_active_selection`).
	 *  3. Backend recomputes canonical scope via `compute_scope`.
	 *  4. Asserts the frontend's `expected_scope` matches the backend's
	 *     `actual_scope` (rejects a stale frontend that raced a provider change).
	 *  5. Writes the selection + consent scope + bumped version in the SAME tx.
	 */
	providerConfirmAndSetActive: (primary: string, parallel: string[], fallback: string | null, expectedScope: string) => __TAURI_INVOKE<number>("provider_confirm_and_set_active", { primary, parallel, fallback, expectedScope }),
	/**
	 *  List the models a provider can use (P1 #8 + plugin-core §7.4).
	 * 
	 *  Local list (current model + catalog default) is always assembled first.
	 *  HTTP GET uses `models_request_url`: if that URL's origin differs from
	 *  `profile.endpoint`, we return an error and **never** attach a key.
	 */
	providerGetModels: (uuid: string) => __TAURI_INVOKE<ModelInfo[]>("provider_get_models", { uuid }),
	/**
	 *  Probe whether a provider is reachable (P1 #8).
	 * 
	 *  Reads the profile snapshot in `spawn_blocking`, then runs an async HEAD-ish
	 *  request against the endpoint. Full connection testing (auth-balanced probe,
	 *  latency buckets, quota introspection) is S3 scope; for now this is a simple
	 *  "could we establish a TCP/TLS connection" check that classifies the outcome.
	 */
	providerTestConnection: (uuid: string) => __TAURI_INVOKE<ConnectionResult_Serialize>("provider_test_connection", { uuid }),
	providerGetBalance: (uuid: string) => __TAURI_INVOKE<BalanceResult>("provider_get_balance", { uuid }),
	openSettingsWindow: (section: string | null) => __TAURI_INVOKE<null>("open_settings_window", { section }),
	shortcutList: () => __TAURI_INVOKE<ShortcutSnapshot>("shortcut_list"),
	shortcutCheckConflict: (action: ShortcutAction, combo: string, revision: number) => __TAURI_INVOKE<"translate_selection" | "translate_input" | "ocr_translate" | "translate_clipboard" | null>("shortcut_check_conflict", { action, combo, revision }),
	shortcutSave: (action: ShortcutAction, combo: string, expectedRevision: number, overrideAction: "translate_selection" | "translate_input" | "ocr_translate" | "translate_clipboard" | null) => __TAURI_INVOKE<ShortcutSnapshot>("shortcut_save", { action, combo, expectedRevision, overrideAction }),
	shortcutResetDefaults: (expectedRevision: number) => __TAURI_INVOKE<ShortcutSnapshot>("shortcut_reset_defaults", { expectedRevision }),
	shortcutRecordingBegin: (action: ShortcutAction) => __TAURI_INVOKE<null>("shortcut_recording_begin", { action }),
	shortcutRecordingEnd: () => __TAURI_INVOKE<void>("shortcut_recording_end"),
	historyPrivacyStatus: () => __TAURI_INVOKE<HistoryPrivacyStatusWire>("history_privacy_status"),
	historySetEnabled: (enabled: boolean) => __TAURI_INVOKE<HistoryPrivacyStatusWire>("history_set_enabled", { enabled }),
	historySetRetention: (days: number) => __TAURI_INVOKE<HistoryPrivacyStatusWire>("history_set_retention", { days }),
	historyClearAll: () => __TAURI_INVOKE<HistoryPrivacyStatusWire>("history_clear_all"),
	historySearch: (query: string, cursor: string | null) => __TAURI_INVOKE<HistoryPage>("history_search", { query, cursor }),
	historyToggleFavorite: (sessionUuid: string) => __TAURI_INVOKE<boolean>("history_toggle_favorite", { sessionUuid }),
	historyDeleteSession: (sessionUuid: string) => __TAURI_INVOKE<null>("history_delete_session", { sessionUuid }),
	historyExport: (filePath: string, format: string, filter: HistoryFilter) => __TAURI_INVOKE<string>("history_export", { filePath, format, filter }),
	vocabularyAdd: (word: string, definition: string, sourceLanguage: string, targetLanguage: string) => __TAURI_INVOKE<VocabularyItem>("vocabulary_add", { word, definition, sourceLanguage, targetLanguage }),
	vocabularyList: (cursor: string | null) => __TAURI_INVOKE<VocabularyPage>("vocabulary_list", { cursor }),
	vocabularyDelete: (itemUuid: string) => __TAURI_INVOKE<null>("vocabulary_delete", { itemUuid }),
	vocabularyExportFile: (filePath: string, format: string) => __TAURI_INVOKE<string>("vocabulary_export_file", { filePath, format }),
	vocabularyExportAnki: (deckName: string) => __TAURI_INVOKE<null>("vocabulary_export_anki", { deckName }),
	dictLookup: (word: string) => __TAURI_INVOKE<{
	definition: string,
	source: string,
} | null>("dict_lookup", { word }),
	dictListPackages: () => __TAURI_INVOKE<DictPackageInfo[]>("dict_list_packages"),
	dictInstallPackage: (sourceDir: string, packageId: string, name: string, version: string) => __TAURI_INVOKE<null>("dict_install_package", { sourceDir, packageId, name, version }),
	/**
	 *  Start an OCR capture session. Tray menu and the OCR hotkey call this.
	 *  `source` records the trigger origin so a stray overlay in the logs can be
	 *  attributed (tray / shortcut / startup anomaly).
	 */
	ocrCapture: (source: string | null) => __TAURI_INVOKE<null>("ocr_capture", { source }),
	ocrCaptureRegion: (x: number, y: number, width: number, height: number) => __TAURI_INVOKE<OcrResult>("ocr_capture_region", { x, y, width, height }),
	ocrFromImage: (path: string) => __TAURI_INVOKE<OcrResult>("ocr_from_image", { path }),
	ocrRecognizeBytes: (bytes: number[]) => __TAURI_INVOKE<OcrResult>("ocr_recognize_bytes", { bytes }),
	ocrFromClipboard: () => __TAURI_INVOKE<OcrResult>("ocr_from_clipboard"),
	ttsSpeak: (text: string, voiceId: string | null) => __TAURI_INVOKE<null>("tts_speak", { text, voiceId }),
	ttsStop: () => __TAURI_INVOKE<void>("tts_stop"),
	externalApiEnable: (port: number | null) => __TAURI_INVOKE<string>("external_api_enable", { port }),
	externalApiStatus: () => __TAURI_INVOKE<ExternalApiStatus>("external_api_status"),
	externalApiDisable: () => __TAURI_INVOKE<null>("external_api_disable"),
	externalApiRegenerateToken: () => __TAURI_INVOKE<string>("external_api_regenerate_token"),
	updaterCheck: () => __TAURI_INVOKE<UpdateCheck>("updater_check"),
	updaterDownloadInstall: () => __TAURI_INVOKE<UpdateCheck>("updater_download_install"),
	onboardingStatus: () => __TAURI_INVOKE<OnboardingStatus>("onboarding_status"),
	/**
	 *  Pure state-machine transition + persistence: the DB is the step source of
	 *  truth, so a mid-flow window close resumes at the persisted step (R6).
	 *  The pure `onboarding::next_step` stays separately unit-tested.
	 */
	onboardingNext: (step: OnboardingStep, event: OnboardingEvent) => __TAURI_INVOKE<OnboardingStep>("onboarding_next", { step, event }),
	onboardingComplete: () => __TAURI_INVOKE<null>("onboarding_complete"),
};

/* Types */
/**
 *  当前 (primary, parallel, fallback) 选择快照，从 `preferences` singleton 读出。
 *  用于 `translate_session` 决定要并行调用哪些引擎。
 */
export type ActiveSelection = {
	/**  primary_uuid；NULL/空 → None。 */
	primary: string | null,
	/**  parallel_uuids JSON 数组解析结果；'[]' → 空 vec。 */
	parallel: string[],
	/**  fallback_uuid；NULL/空 → None。 */
	fallback: string | null,
};

export type AuthKind = "bearer" | "x-api-key" | "azure-key" | "query" | "none";

export type BalanceResult = { kind: "unsupported" } | { kind: "ok"; balance: string; quota: string | null } | { kind: "error"; message: string };

export type CatalogPresetDto = {
	id: string,
	label: string,
	endpoint: string,
	default_model: string,
	needs_key: boolean,
	auth: AuthKind,
	requires_user_endpoint: boolean,
	notes: string | null,
	console_url: string | null,
	support_tier: SupportTier,
	icon: string | null,
};

/**
 *  Result of a connection probe (P1 #8). `ok` + a human-readable message; the
 *  full connection-test HTTP flow is S3 scope, so the current implementation is
 *  a best-effort "reachable" check.
 * 
 *  `latency_ms` is `Some(ms)` only on the reachable arm (a real Instant probe
 *  of the HTTP round-trip); it is `None` on every early-exit failure arm
 *  (empty/invalid endpoint, transport error, missing HTTP client).
 */
export type ConnectionResult = ConnectionResult_Serialize | ConnectionResult_Deserialize;

/**
 *  Result of a connection probe (P1 #8). `ok` + a human-readable message; the
 *  full connection-test HTTP flow is S3 scope, so the current implementation is
 *  a best-effort "reachable" check.
 * 
 *  `latency_ms` is `Some(ms)` only on the reachable arm (a real Instant probe
 *  of the HTTP round-trip); it is `None` on every early-exit failure arm
 *  (empty/invalid endpoint, transport error, missing HTTP client).
 */
export type ConnectionResult_Deserialize = {
	ok: boolean,
	message: string,
	latency_ms: number | null,
};

/**
 *  Result of a connection probe (P1 #8). `ok` + a human-readable message; the
 *  full connection-test HTTP flow is S3 scope, so the current implementation is
 *  a best-effort "reachable" check.
 * 
 *  `latency_ms` is `Some(ms)` only on the reachable arm (a real Instant probe
 *  of the HTTP round-trip); it is `None` on every early-exit failure arm
 *  (empty/invalid endpoint, transport error, missing HTTP client).
 */
export type ConnectionResult_Serialize = {
	ok: boolean,
	message: string,
	latency_ms?: number | null,
};

export type DecryptedHistoryResult = {
	result_uuid: string,
	provider_uuid: string,
	provider_name: string,
	engine_id: string,
	elapsed_ms: number,
	outcome_tag: string,
	text: string | null,
	error_kind: string | null,
	error_message: string | null,
	corrupt: boolean,
};

export type DecryptedHistorySession = {
	session_uuid: string,
	timestamp: number,
	trigger_source: string,
	detected_language: string | null,
	target_language: string,
	is_favorite: boolean,
	source_text: string | null,
	results: DecryptedHistoryResult[],
	corrupt: boolean,
};

export type DictLookupResult = {
	definition: string,
	source: string,
};

export type DictPackageInfo = {
	package_id: string,
	name: string,
	version: string,
	installed_at: number,
};

export type ExternalApiStatus = { state: "disabled" } | { state: "enabled"; port: number } | { state: "port_in_use"; configured_port: number };

/**  Filter applied during export. Empty `query` means all retained sessions. */
export type HistoryFilter = {
	query: string | null,
	favorites_only?: boolean,
};

export type HistoryPage = {
	items: DecryptedHistorySession[],
	next_cursor: string | null,
	scan_complete: boolean,
};

export type HistoryPrivacyStatusWire = {
	enabled: boolean,
	retention_days: number,
	record_count: number,
};

/**
 *  One selectable model for a provider. Assembled from the local profile
 *  (current model + catalog default) then extended by an HTTP GET to
 *  `models_request_url` when the origin matches.
 */
export type ModelInfo = {
	id: string,
	label: string,
};

export type OcrResult = {
	text: string,
	confidence: number | null,
};

export type OnboardingEvent = "start" | "continue" | "skip" | "complete";

export type OnboardingStatus = {
	complete: boolean,
	step: OnboardingStep,
};

export type OnboardingStep = "welcome" | "accessibility" | "provider" | "history" | "shortcuts" | "done";

/**
 *  Wire protocol family. Stored as TEXT in the `providers` table; the serde
 *  snake_case names are exactly the CHECK-constraint whitelist in schema.rs.
 */
export type Protocol = "openai_chat" | "anthropic" | "gemini" | "google_translate" | "custom_http" | "deepl" | "microsoft" | "baidu" | "youdao" | "tencent";

/**
 *  Feature flags a provider advertises. Stored as a JSON object in the
 *  `capabilities` TEXT column (`{"balance":false,"quota":false,"model_list":false}`).
 *  All-`false` is the default (most providers don't expose balance/quota/model-list).
 */
export type ProviderCapabilities = ProviderCapabilities_Serialize | ProviderCapabilities_Deserialize;

/**
 *  Feature flags a provider advertises. Stored as a JSON object in the
 *  `capabilities` TEXT column (`{"balance":false,"quota":false,"model_list":false}`).
 *  All-`false` is the default (most providers don't expose balance/quota/model-list).
 */
export type ProviderCapabilities_Deserialize = {
	balance: boolean,
	quota: boolean,
	model_list: boolean,
	auth?: AuthKind | null,
	models_url?: string | null,
};

/**
 *  Feature flags a provider advertises. Stored as a JSON object in the
 *  `capabilities` TEXT column (`{"balance":false,"quota":false,"model_list":false}`).
 *  All-`false` is the default (most providers don't expose balance/quota/model-list).
 */
export type ProviderCapabilities_Serialize = {
	balance: boolean,
	quota: boolean,
	model_list: boolean,
	auth?: AuthKind | null,
	models_url?: string | null,
};

/**
 *  Structured error type for provider IPC commands (P1.1 fix).
 *  Replaces free-form `String` errors so the frontend can pattern-match
 *  instead of parsing string prefixes.
 *  Wire shape for StaleScope: `{"error":"stale_scope","actual_scope":"..."}`
 *  Wire shape for StaleVersion (R2-E): `{"error":"stale_version","actual_version":N}`
 */
export type ProviderCommandError = { error: "stale_scope"; actual_scope: string } | 
/**
 *  Optimistic-lock mismatch (R2-E): the provider row was modified elsewhere
 *  since the frontend last read it. Carries the row's actual version so the
 *  UI can prompt a reload.
 */
{ error: "stale_version"; actual_version: number } | 
/**  Generic database or validation error. */
{ error: "db"; message: string } | 
/**  Provider not found, invalid selection, etc. */
{ error: "validation"; message: string };

/**
 *  Patch body for [`update`]. `#[serde(deny_unknown_fields)]` so the API layer
 *  rejects typo'd field names instead of silently dropping them.
 * 
 *  `expected_version` is REQUIRED (R2-E optimistic lock): it must equal the
 *  row's current `version` for the CAS UPDATE to match. There is no bypass —
 *  the frontend always sends the last-read version, and a mismatch surfaces as
 *  [`UpdateOutcome::StaleVersion`].
 */
export type ProviderPatch = {
	name: string | null,
	endpoint: string | null,
	model: string | null,
	enabled: boolean | null,
	sort_order: number | null,
	expected_version: number,
	protocol?: Protocol | null,
};

/**
 *  One row of the `providers` table.
 * 
 *  `status` is kept as a raw `String` (not `ProviderStatus`) so the row type is
 *  a faithful mirror of the DB column — callers that need the typed form parse
 *  it explicitly. This also keeps (de)serialization lossless for rows whose
 *  status string the enum doesn't model yet.
 */
export type ProviderProfile = ProviderProfile_Serialize | ProviderProfile_Deserialize;

/**
 *  One row of the `providers` table.
 * 
 *  `status` is kept as a raw `String` (not `ProviderStatus`) so the row type is
 *  a faithful mirror of the DB column — callers that need the typed form parse
 *  it explicitly. This also keeps (de)serialization lossless for rows whose
 *  status string the enum doesn't model yet.
 */
export type ProviderProfile_Deserialize = {
	uuid: string,
	template_id: string,
	name: string,
	protocol: Protocol,
	endpoint: string,
	model: string | null,
	enabled: boolean,
	sort_order: number,
	is_local: boolean,
	needs_key: boolean,
	secret_ref: string,
	capabilities: ProviderCapabilities_Deserialize,
	/**  `"active" | "deleting" | "deleted"`. */
	status: string,
	/**
	 *  Optimistic-lock version (R2-E). Starts at 1 on create/insert and is
	 *  bumped by every successful [`update`]. The frontend echoes back the
	 *  last-read value as `ProviderPatch::expected_version`; a mismatch
	 *  (someone else wrote first) yields [`UpdateOutcome::StaleVersion`].
	 */
	version: number,
};

/**
 *  One row of the `providers` table.
 * 
 *  `status` is kept as a raw `String` (not `ProviderStatus`) so the row type is
 *  a faithful mirror of the DB column — callers that need the typed form parse
 *  it explicitly. This also keeps (de)serialization lossless for rows whose
 *  status string the enum doesn't model yet.
 */
export type ProviderProfile_Serialize = {
	uuid: string,
	template_id: string,
	name: string,
	protocol: Protocol,
	endpoint: string,
	model: string | null,
	enabled: boolean,
	sort_order: number,
	is_local: boolean,
	needs_key: boolean,
	secret_ref: string,
	capabilities: ProviderCapabilities_Serialize,
	/**  `"active" | "deleting" | "deleted"`. */
	status: string,
	/**
	 *  Optimistic-lock version (R2-E). Starts at 1 on create/insert and is
	 *  bumped by every successful [`update`]. The frontend echoes back the
	 *  last-read value as `ProviderPatch::expected_version`; a mismatch
	 *  (someone else wrote first) yields [`UpdateOutcome::StaleVersion`].
	 */
	version: number,
};

/**
 *  Result of [`provider_set_active`] (P1.1). A serializable tagged union so the
 *  frontend distinguishes "written" from "needs consent" via a structured
 *  payload instead of parsing an error string.
 * 
 *  Wire shapes:
 *  - `Written` → `{"outcome":"written"}`
 *  - `NeedsConsent { actual_scope }` → `{"outcome":"needs_consent","actual_scope":"..."}`
 */
export type SetActiveResult = 
/**  The selection was written (no consent needed, or scope already matched). */
{ outcome: "written" } | 
/**
 *  A non-empty parallel selection needs explicit consent; carries the
 *  canonical scope the frontend must echo back via
 *  `provider_confirm_and_set_active`.
 */
{ outcome: "needs_consent"; actual_scope: string };

export type Settings = {
	default_provider: string,
	target_language: string,
	/**
	 *  §G: cross-remote fallback is OPT-IN. `None` (default) = no fallback; the
	 *  user must explicitly choose a traditional engine to consent to their text
	 *  being sent to a second remote endpoint. Set to a `TraditionalEngine` id
	 *  (e.g. "google") to enable the single AI→trad fallback attempt.
	 */
	fallback_engine: string | null,
	/**
	 *  R5: startup update check. ON by default; the README privacy section
	 *  documents it as the app's only unsolicited network request (GitHub
	 *  Releases). Users who want zero outbound traffic can turn it off.
	 */
	check_updates_on_startup: boolean,
};

/**  Stable identifiers used by the frontend and persisted in SQLite. */
export type ShortcutAction = "translate_selection" | "translate_input" | "ocr_translate" | "translate_clipboard";

export type ShortcutEntry = {
	action: ShortcutAction,
	combo: string,
	available: boolean,
	registration_state: ShortcutRegistrationState,
	registration_error: string | null,
	recording: boolean,
};

export type ShortcutError = { error: "invalid_combo"; message: string } | { error: "unavailable"; action: ShortcutAction } | { error: "conflict"; action: ShortcutAction } | { error: "stale_revision"; expected: number; actual: number } | { error: "invalid_override"; action: ShortcutAction } | { error: "registration_failed"; message: string } | { error: "database_failed"; message: string } | { error: "rollback_failed"; operation: string; rollback: string };

export type ShortcutRegistrationState = "registered" | "registration_failed" | "unavailable";

export type ShortcutSnapshot = {
	revision: number,
	entries: ShortcutEntry[],
};

export type SupportTier = "ready" | "setup_required" | "unverified";

export type TranslateSessionRequest = {
	text: string,
	from: string,
	to: string,
};

/**
 *  Frontend-facing session result. The service keeps Rust's `Result` internally;
 *  the IPC contract flattens each outcome into stable `ok/text/error` fields.
 */
export type TranslateSessionWire = TranslateSessionWire_Serialize | TranslateSessionWire_Deserialize;

/**
 *  Frontend-facing session result. The service keeps Rust's `Result` internally;
 *  the IPC contract flattens each outcome into stable `ok/text/error` fields.
 */
export type TranslateSessionWire_Deserialize = {
	outcomes: TranslationOutcomeSerialized_Deserialize[],
	actual_engine: string | null,
};

/**
 *  Frontend-facing session result. The service keeps Rust's `Result` internally;
 *  the IPC contract flattens each outcome into stable `ok/text/error` fields.
 */
export type TranslateSessionWire_Serialize = {
	outcomes: TranslationOutcomeSerialized_Serialize[],
	actual_engine?: string | null,
};

/**  单个引擎结果的序列化形态（前端友好：Result 拆成 ok + text/error 扁平字段）。 */
export type TranslationOutcomeSerialized = TranslationOutcomeSerialized_Serialize | TranslationOutcomeSerialized_Deserialize;

/**  单个引擎结果的序列化形态（前端友好：Result 拆成 ok + text/error 扁平字段）。 */
export type TranslationOutcomeSerialized_Deserialize = {
	uuid: string,
	ok: boolean,
	text: string | null,
	engine: string | null,
	error: string | null,
};

/**  单个引擎结果的序列化形态（前端友好：Result 拆成 ok + text/error 扁平字段）。 */
export type TranslationOutcomeSerialized_Serialize = {
	uuid: string,
	ok: boolean,
	text?: string | null,
	engine?: string | null,
	error?: string | null,
};

export type UpdateCheck = { state: "up_to_date"; version: string } | { state: "available"; current: string; next: string; notes: string } | { state: "error"; message: string };

export type VocabularyItem = {
	item_uuid: string,
	timestamp: number,
	source_language: string,
	target_language: string,
	word: string,
	definition: string,
};

export type VocabularyPage = {
	items: VocabularyItem[],
	next_cursor: string | null,
	scan_complete: boolean,
};

