include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - windows/**
    - macos/**
    - android/**
    - ios/**
    - web/**
    - linux/**

linter:
  rules:
    always_use_package_imports: true
    directives_ordering: true
    prefer_single_quotes: true
    sort_constructors_first: true
