// This file is automatically generated. Do not edit by hand.
// Source: scripts/generate/data/languages.json

use beyondtranslate_core::LanguageInfo;

/// Returns the curated language list supported by the app.
pub fn all_languages() -> Vec<LanguageInfo> {
    supported_languages()
}

/// Returns languages supported by the app UI.
pub fn app_languages() -> Vec<LanguageInfo> {
    let app_language_codes = ["en", "es", "fr", "ja", "ko", "zh-Hans", "zh-Hant"];
    let languages = supported_languages();
    app_language_codes
        .into_iter()
        .filter_map(|code| {
            languages
                .iter()
                .find(|language| language.code == code)
                .cloned()
        })
        .collect()
}

fn supported_languages() -> Vec<LanguageInfo> {
    vec![
        LanguageInfo {
            code: "ar".to_owned(),
            local_name: "العربية".to_owned(),
        },
        LanguageInfo {
            code: "bn".to_owned(),
            local_name: "বাংলা".to_owned(),
        },
        LanguageInfo {
            code: "de".to_owned(),
            local_name: "Deutsch".to_owned(),
        },
        LanguageInfo {
            code: "en".to_owned(),
            local_name: "English".to_owned(),
        },
        LanguageInfo {
            code: "es".to_owned(),
            local_name: "Español".to_owned(),
        },
        LanguageInfo {
            code: "fa".to_owned(),
            local_name: "فارسی".to_owned(),
        },
        LanguageInfo {
            code: "fr".to_owned(),
            local_name: "Français".to_owned(),
        },
        LanguageInfo {
            code: "gu".to_owned(),
            local_name: "ગુજરાતી".to_owned(),
        },
        LanguageInfo {
            code: "ha".to_owned(),
            local_name: "Hausa".to_owned(),
        },
        LanguageInfo {
            code: "hi".to_owned(),
            local_name: "हिन्दी".to_owned(),
        },
        LanguageInfo {
            code: "id".to_owned(),
            local_name: "Bahasa Indonesia".to_owned(),
        },
        LanguageInfo {
            code: "it".to_owned(),
            local_name: "Italiano".to_owned(),
        },
        LanguageInfo {
            code: "ja".to_owned(),
            local_name: "日本語".to_owned(),
        },
        LanguageInfo {
            code: "jv".to_owned(),
            local_name: "Basa Jawa".to_owned(),
        },
        LanguageInfo {
            code: "ko".to_owned(),
            local_name: "한국어".to_owned(),
        },
        LanguageInfo {
            code: "ml".to_owned(),
            local_name: "മലയാളം".to_owned(),
        },
        LanguageInfo {
            code: "mr".to_owned(),
            local_name: "मराठी".to_owned(),
        },
        LanguageInfo {
            code: "ms".to_owned(),
            local_name: "Bahasa Melayu".to_owned(),
        },
        LanguageInfo {
            code: "nl".to_owned(),
            local_name: "Nederlands".to_owned(),
        },
        LanguageInfo {
            code: "pa".to_owned(),
            local_name: "ਪੰਜਾਬੀ".to_owned(),
        },
        LanguageInfo {
            code: "pl".to_owned(),
            local_name: "Polski".to_owned(),
        },
        LanguageInfo {
            code: "pt".to_owned(),
            local_name: "Português".to_owned(),
        },
        LanguageInfo {
            code: "ro".to_owned(),
            local_name: "Română".to_owned(),
        },
        LanguageInfo {
            code: "ru".to_owned(),
            local_name: "Русский".to_owned(),
        },
        LanguageInfo {
            code: "sw".to_owned(),
            local_name: "Kiswahili".to_owned(),
        },
        LanguageInfo {
            code: "ta".to_owned(),
            local_name: "தமிழ்".to_owned(),
        },
        LanguageInfo {
            code: "te".to_owned(),
            local_name: "తెలుగు".to_owned(),
        },
        LanguageInfo {
            code: "th".to_owned(),
            local_name: "ไทย".to_owned(),
        },
        LanguageInfo {
            code: "tr".to_owned(),
            local_name: "Türkçe".to_owned(),
        },
        LanguageInfo {
            code: "uk".to_owned(),
            local_name: "Українська".to_owned(),
        },
        LanguageInfo {
            code: "ur".to_owned(),
            local_name: "اردو".to_owned(),
        },
        LanguageInfo {
            code: "vi".to_owned(),
            local_name: "Tiếng Việt".to_owned(),
        },
        LanguageInfo {
            code: "yo".to_owned(),
            local_name: "Yoruba".to_owned(),
        },
        LanguageInfo {
            code: "zh-Hans".to_owned(),
            local_name: "中文（简体）".to_owned(),
        },
        LanguageInfo {
            code: "zh-Hant".to_owned(),
            local_name: "中文（繁體）".to_owned(),
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_languages_is_not_empty() {
        let languages = all_languages();
        assert!(!languages.is_empty());
    }

    #[test]
    fn test_all_languages_has_no_duplicates() {
        let languages = all_languages();
        let mut codes = languages
            .iter()
            .map(|l| l.code.as_str())
            .collect::<Vec<_>>();
        codes.sort_unstable();
        codes.dedup();
        assert_eq!(codes.len(), languages.len());
    }

    #[test]
    fn test_all_languages_has_common_languages() {
        let languages = all_languages();
        let codes = languages
            .iter()
            .map(|l| l.code.as_str())
            .collect::<Vec<_>>();
        assert!(codes.contains(&"en"));
        assert!(codes.contains(&"zh-Hans"));
        assert!(codes.contains(&"zh-Hant"));
        assert!(codes.contains(&"ja"));
        assert!(codes.contains(&"ko"));
        assert!(codes.contains(&"fr"));
        assert!(codes.contains(&"de"));
        assert!(codes.contains(&"es"));
        assert!(codes.contains(&"ru"));
        assert!(codes.contains(&"ar"));
        assert!(codes.contains(&"jv"));
        assert!(!codes.contains(&"iw"));
        assert!(!codes.contains(&"jw"));
        assert!(!codes.contains(&"kIs"));
    }

    #[test]
    fn test_all_languages_local_names_are_populated() {
        let languages = all_languages();
        for lang in &languages {
            assert!(
                !lang.local_name.is_empty(),
                "local_name for {} is empty",
                lang.code
            );
        }
    }

    #[test]
    fn test_app_languages_are_subset_of_all_languages() {
        let languages = all_languages();
        let app_languages = app_languages();
        assert!(!app_languages.is_empty());
        for app_language in &app_languages {
            assert!(languages
                .iter()
                .any(|language| language.code == app_language.code));
        }
    }
}
